language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t sugurukabashima/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sugurukabashima/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-804203453874"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY